In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
a.shape, a.dtype, a.size, a.ndim, a.itemsize

((2, 3), dtype('int64'), 6, 2, 8)

In [3]:
b = np.array([[1,2,3],[3,4,6]])
np.unique(b)

array([1, 2, 3, 4, 6])

In [4]:
a0 = [[1,2,3], [4,5,6]]
c = np.array(a0, dtype=np.int32)
c.dtype

dtype('int32')

In [6]:
np.ones((3,2)), np.ones_like(a0), np.zeros((3,4)), np.zeros_like(a0)

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[1, 1, 1],
        [1, 1, 1]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[0, 0, 0],
        [0, 0, 0]]))

In [9]:
np.linspace(1, 100, 50), np.logspace(1, 100, 10)

(array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
         25.24489796,  27.26530612,  29.28571429,  31.30612245,
         33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
         65.65306122,  67.67346939,  69.69387755,  71.71428571,
         73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
         81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]),
 array([1.e+001, 1.e+012, 1.e+023, 1.e+034, 1.e+045, 1.e+056, 1.e+067,
        1.e+078, 1.e+089, 1.e+100]))

In [10]:
1.e+100

1e+100

In [11]:
np.random.rand(2,3,4)


array([[[0.11763509, 0.16820194, 0.16818491, 0.08865598],
        [0.4810735 , 0.56868038, 0.80707333, 0.65078867],
        [0.24174353, 0.5715994 , 0.82164559, 0.18533895]],

       [[0.70325323, 0.71321327, 0.48274247, 0.07357046],
        [0.31528244, 0.89967792, 0.10685056, 0.16026392],
        [0.36859256, 0.8742453 , 0.06288739, 0.11307735]]])

In [12]:
np.random.uniform()

0.825619384053368

In [13]:
np.random.randn(2,3), np.random.normal(3,4, (2,3))

(array([[-0.86202316, -0.29243184, -0.96239532],
        [-0.63739334, -1.04367406,  2.29320414]]),
 array([[ 1.63532316, -0.23358143, -5.46724285],
        [ 3.89868013, -2.9247204 ,  0.26180232]]))

In [15]:
a1 = np.array(a0)
a1.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a1.resize([1,6])

In [19]:
a1.reshape(6, -1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [20]:
a1.dtype

dtype('int64')

In [21]:
a1.astype(np.int32), a1.dtype

(array([[1, 2, 3, 4, 5, 6]], dtype=int32), dtype('int64'))

In [22]:
#ndarray运算

In [24]:
#生成10名同学，5门功课的数据
score  = np.random.randint(40, 100, (10, 5))
score

array([[71, 91, 46, 46, 80],
       [70, 59, 41, 99, 59],
       [89, 69, 50, 46, 42],
       [62, 68, 73, 98, 94],
       [76, 60, 70, 42, 80],
       [40, 76, 41, 70, 61],
       [41, 81, 49, 87, 67],
       [94, 75, 79, 41, 83],
       [97, 82, 87, 60, 74],
       [80, 65, 99, 73, 82]])

In [26]:
test_score = score[6:, :]
test_score

array([[41, 81, 49, 87, 67],
       [94, 75, 79, 41, 83],
       [97, 82, 87, 60, 74],
       [80, 65, 99, 73, 82]])

In [27]:
test_score > 60

array([[False,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [28]:
test_score[test_score > 60] = 1
test_score

array([[41,  1, 49,  1,  1],
       [ 1,  1,  1, 41,  1],
       [ 1,  1,  1, 60,  1],
       [ 1,  1,  1,  1,  1]])

In [29]:
np.all(score[:2, :] > 60), np.any(score[:2, :] > 80)

(False, True)

In [30]:
temp = score[:4, :4]
temp

array([[71, 91, 46, 46],
       [70, 59, 41, 99],
       [89, 69, 50, 46],
       [62, 68, 73, 98]])

In [31]:
np.where(temp > 60, 1, 0)

array([[1, 1, 0, 0],
       [1, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [32]:
np.where(np.logical_and(temp > 60, temp < 90),1, 0)

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0]])

In [35]:
np.where(np.logical_or(temp < 60, temp > 90), 1, 0)

array([[0, 1, 1, 1],
       [0, 1, 1, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 1]])

In [34]:
temp

array([[71, 91, 46, 46],
       [70, 59, 41, 99],
       [89, 69, 50, 46],
       [62, 68, 73, 98]])

In [38]:
np.min(temp, axis=0), np.max(temp, axis=1)

(array([62, 59, 41, 46]), array([91, 99, 89, 98]))

In [39]:
score

array([[71, 91, 46, 46, 80],
       [70, 59, 41, 99, 59],
       [89, 69, 50, 46, 42],
       [62, 68, 73, 98, 94],
       [76, 60, 70, 42, 80],
       [40, 76, 41, 70, 61],
       [41,  1, 49,  1,  1],
       [ 1,  1,  1, 41,  1],
       [ 1,  1,  1, 60,  1],
       [ 1,  1,  1,  1,  1]])

In [40]:
score.min()

1